#!/bin/sh
# TODO: remove this file after releasing Squeeze
set -e

PYCENTRAL=/usr/bin/pycentral

if [ "$1" = upgrade ]
then
       if dpkg --compare-versions "$2" lt 0.3.0-2 ; then
	   if [ -x $PYCENTRAL ]; then
               # explicitly remove old python-central files
               pycentral pkgremove pyflakes
	   fi
	   # be really sure also removing left-over files and dirs
	   rm -rf /usr/lib/python2.5/site-packages/pyflakes*
       fi
fi

#DEBHELPER#
